name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build package
        run: nix develop --command npm run build

      - name: Publish to npm
        working-directory: ./dist
        run: nix develop --command npm publish --registry https://registry.npmjs.org/ --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
